### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AngeloNetDev** [AngeloDotNet/NET6CustomLibrary#2]
Add extensions methods documentation

**Comment by AngeloDotNet** [comment]
Added documentation for SERILOG

**Comment by AngeloDotNet** [comment]
Added documentation for MULTI LANGUAGE

**Comment by AngeloDotNet** [comment]
Added documentation for DATE and TIME ONLY

**Comment by AngeloDotNet** [comment]
Added documentation for:

- Json
- DbContextPool for MySQL database
- Health Checks for MySQL database

**Comment by AngeloDotNet** [comment]
Added documentation for MAILKIT

**Comment by AngeloDotNet** [comment]
This issue is closed as documentation is added whenever a new implementation is added
